language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
before_install:
    - pip install pip
    - pip install pytest
install:
    - pip install -r requirements.txt
    - pip install .
script:
    pytest
